import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import expenseGrid1 from "@/utils/images/expenseGrid1.jpg";
import React, { useState } from "react";
import Modal from "@/components/modal/modal";

export default function Home() {
  const [showModal, setShowModal] = useState(false);

  const handleImageClick = () => {
    setShowModal(true);
  }

  const handleCloseModal = () => {
    setShowModal(false);
  }
  

  return (
    <>
      <Head>
        <title>Expenses Analytics</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Cedarville+Cursive&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main className={styles.main}>
        <div className={styles.intro}>
          <h2>Welcome</h2>
          <p>
            "Track Your Spending, Empower Your Saving: Simplify Your Finances
            with Our Expense Calculator"
          </p>
        </div>
        <div className={styles.expenseSection}>
          <div className={styles.expenseGrid1}>
            <Image
              src={expenseGrid1}
              alt="Expense Grid"
              className={styles.expenseGridImg}
              onClick={handleImageClick}
            />
            <Modal showModal={showModal} handleClose={handleCloseModal} />
          </div>
        </div>
      </main>
    </>
  );
}
